### ISSUE TITLE
10주차 최소비용트리

### ISSUE THREAD

**Issue by kinnyeri** [DewPeaceTigers/AlgorithmStudy#34]
- 크루스칼, 프림, 유니온파인드
[BOJ 9372 실버3](https://www.acmicpc.net/problem/9372)
[BOJ 4386 골드4](https://www.acmicpc.net/problem/4386)
[BOJ 1197 골드4](https://www.acmicpc.net/problem/1197)
[BOJ 1922 골드4](https://www.acmicpc.net/problem/1922)
[PG 49191 LV3](https://programmers.co.kr/learn/courses/30/lessons/49191)
[BOJ 1339 골드4](https://www.acmicpc.net/problem/1339)
[BOJ 4796 실버5](https://www.acmicpc.net/problem/4796)

**Comment by kinnyeri** [comment]
[정리](https://velog.io/@kinnyeri/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-10%EC%A3%BC%EC%B0%A8-%EC%B5%9C%EC%86%8C-%EB%B9%84%EC%9A%A9-%ED%8A%B8%EB%A6%AC)

**Comment by Min-ji99** [comment]
[민지 정리](https://velog.io/@min-ji99/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EC%B5%9C%EC%86%8C-%EB%B9%84%EC%9A%A9-%EC%8B%A0%EC%9E%A5-%ED%8A%B8%EB%A6%AC)

**Comment by charmdew** [comment]
[정민 정리](https://velog.io/@ryujm/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EC%B5%9C%EC%86%8C%EC%8B%A0%EC%9E%A5%ED%8A%B8%EB%A6%AC)

**Comment by kinnyeri** [comment]
https://www.acmicpc.net/workbook/view/4289

**Comment by kinnyeri** [comment]
1197 - 정민이(힙)과 속도 비교하기

**Comment by kinnyeri** [comment]
print("Case {}: {}".format(i+1, ans[i]))
